### ISSUE TITLE
panicked: "attempted to leave type `&mpi::request::LocalScope` uninitialized, which is invalid"

### ISSUE THREAD

**Issue by fzyzcjy** [rsmpi/rsmpi#94]
I am running the example code in README.md. 

Command: `RUST_BACKTRACE=full cargo mpirun --all-features --verbose -n 2 --bin trans_sort`

It goes well and output correctly. But when exiting the `mpi::request::scope(|| ... )` it panicks.

Looking into stacktrace (`mpi-0.5.4/src/request.rs:109`), there is:

```
...
    /// Unregister the request object from its scope and deconstruct it into its raw parts.
    ///
    /// This is unsafe because the request may outlive its associated buffers.
    pub unsafe fn into_raw(mut self) -> (MPI_Request, S) {
        let request = mem::replace(&mut self.request, mem::uninitialized());
        let scope = mem::replace(&mut self.scope, mem::uninitialized()); // <-- 109!!!
        let _ = mem::replace(&mut self.phantom, mem::uninitialized());
        mem::forget(self);
        scope.unregister();
        (request, scope)
    }
...
```

And I see from https://github.com/rust-lang/rust/pull/66059 that, in 2020 March, a new PR is merged. It says "**panic on types that do not permit zero-initialization**".

Moreover, when I read `mem::uninitialized`'s documentation, it says it is **deprecated** and cannot be used correctly.

So I guess this is the problem, and maybe `mem::uninitialized()` should be changed to something like `MaybeUninit::uninit().assume_init()`?

Sorry if I am wrong. I am really new to Rust. Anyway thanks very much for this lib!

P.S. The Travis CI is even *passing*... https://travis-ci.org/github/rsmpi/rsmpi I am confused why it can happen...

Stacktrace:

```
thread 'main' panicked at 'attempted to leave type `&mpi::request::LocalScope` uninitialized, which is invalid', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/mem/mod.rs:664:9
stack backtrace:
   0:     0x5564c17b9005 - backtrace::backtrace::libunwind::trace::h14d338b30b3ea0a7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x5564c17b9005 - backtrace::backtrace::trace_unsynchronized::h73ea91d74a3fd67f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x5564c17b9005 - std::sys_common::backtrace::_print_fmt::hd42948c952866e12
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5564c17b9005 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha8f928866ff7571e
                               at src/libstd/sys_common/backtrace.rs:59
   0:     0x5607ab178005 - backtrace::backtrace::libunwind::trace::h14d338b30b3ea0a7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x5607ab178005 - backtrace::backtrace::trace_unsynchronized::h73ea91d74a3fd67f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x5607ab178005 - std::sys_common::backtrace::_print_fmt::hd42948c952866e12
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5607ab178005 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha8f928866ff7571e
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5564c17d5d4c - core::fmt::write::he0c1e5f7426d2718
                               at src/libcore/fmt/mod.rs:1076
   5:     0x5564c17b73f2 - std::io::Write::write_fmt::hf3afc6cfd57d0033
                               at src/libstd/io/mod.rs:1537
   6:     0x5564c17bb440 - std::sys_common::backtrace::_print::hfc0110703f3696fd
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5564c17bb440 - std::sys_common::backtrace::print::h3f77c6990ddfaa22
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5564c17bb440 - std::panicking::default_hook::{{closure}}::heae49580a8d62d75
                               at src/libstd/panicking.rs:198
   9:     0x5564c17bb18c - std::panicking::default_hook::hecc34e3f729e213c
                               at src/libstd/panicking.rs:217
  10:     0x5564c17bba83 - std::panicking::rust_panic_with_hook::he82f5d0644692441
                               at src/libstd/panicking.rs:526
  11:     0x5564c17bb67b - rust_begin_unwind
                               at src/libstd/panicking.rs:437
  12:     0x5564c17d5151 - core::panicking::panic_fmt::h09c929f06bb87c98
                               at src/libcore/panicking.rs:85
  13:     0x5564c17d509d - core::panicking::panic::h7ece43057e5422d4
                               at src/libcore/panicking.rs:50
  14:     0x5564c17a6bf1 - core::mem::uninitialized::hb13e4a6bd3d9fb2f
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/mem/mod.rs:664
  15:     0x5564c17a6bf1 - mpi::request::Request<S>::into_raw::haa729e7e2738a9f3
                               at /home/cuhksz_csc/.cargo/registry/src/github.com-1ecc6299db9ec823/mpi-0.5.4/src/request.rs:109
  16:     0x5564c17a6ce7 - mpi::request::Request<S>::wait_with::hc3e821c32602b74e
                               at /home/cuhksz_csc/.cargo/registry/src/github.com-1ecc6299db9ec823/mpi-0.5.4/src/request.rs:121
  17:     0x5564c17a6a10 - mpi::request::Request<S>::wait::h344d92dd4ef4055e
                               at /home/cuhksz_csc/.cargo/registry/src/github.com-1ecc6299db9ec823/mpi-0.5.4/src/request.rs:144
  18:     0x5564c17a7be4 - <mpi::request::WaitGuard<S> as core::ops::drop::Drop>::drop::h99e86b377587ee7f
                               at /home/cuhksz_csc/.cargo/registry/src/github.com-1ecc6299db9ec823/mpi-0.5.4/src/request.rs:234
  19:     0x5564c17a7a32 - core::ptr::drop_in_place::h056458675d996bd3
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/ptr/mod.rs:184
  20:     0x5564c17a9067 - trans_sort::main::{{closure}}::h0b6ea2009f297340
                               at src/main.rs:55
  21:     0x5564c17a6de2 - mpi::request::scope::h388effd1a74050b9
                               at /home/cuhksz_csc/.cargo/registry/src/github.com-1ecc6299db9ec823/mpi-0.5.4/src/request.rs:403
  22:     0x5564c17a6638 - trans_sort::main::haba3f992747c3029
                               at src/main.rs:19
  23:     0x5564c17a7c5b - std::rt::lang_start::{{closure}}::heb816d03eafe061e
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
  24:     0x5564c17bbe53 - std::rt::lang_start_internal::{{closure}}::h5d3ea623498f5f43
                               at src/libstd/rt.rs:52
  25:     0x5564c17bbe53 - std::panicking::try::do_call::hac65e71be769a440
                               at src/libstd/panicking.rs:348
  26:     0x5564c17bbe53 - std::panicking::try::hd4706e264bcf6712
                               at src/libstd/panicking.rs:325
  27:     0x5564c17bbe53 - std::panic::catch_unwind::h948a0fb4a8b3ee82
                               at src/libstd/panic.rs:394
  28:     0x5564c17bbe53 - std::rt::lang_start_internal::h72cc068ed2d0ac53
                               at src/libstd/rt.rs:51
  29:     0x5564c17a7c37 - std::rt::lang_start::h335e4fe997dbbc83
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
  30:     0x5564c17a67ea - main
  31:     0x7f4f98c26b97 - __libc_start_main
  32:     0x5564c17a612a - _start
  33:                0x0 - <unknown>
```

**Comment by adamreichold** [comment]
This is already fixed on `master` and unrelated to the issue discussed in #75. ATM, it seems best to use a Git dependency
```
mpi = { git = "https://github.com/rsmpi/rsmpi.git" }
```
as this crate approaches version 0.6.

**Comment by fzyzcjy** [comment]
@adamreichold Thanks very much! I will try that. By the way, when will 0.6 be officially released - is 0.6 stable enough, or will it have other (more) bugs

**Comment by AndrewGaspar** [comment]
You know I'd love some help to get the `0.6` release out. :)

**Comment by AndrewGaspar** [comment]
I'll try to make a list this evening of things that need to be done for a `0.6` release, if you're interested.
